debug e2e testing

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -39,12 +39,12 @@ jobs:
         chromedriver-version: '126.0.6478.182'
     - run: |
         export DISPLAY=:99
-        chromedriver --url-base=/wd/hub &
+        chromedriver --url-base=/wd/hub > driver.txt &
 
     - name: Run website
       run: |
         npx wrangler@latest build
-        npx wrangler@latest dev &
+        npx wrangler@latest dev > dev.txt &
         echo "waiting"
         timeout 120 sh -c 'until nc -z $0 $1; do sleep 1; done' 127.0.0.1 8787
         curl 127.0.0.1:8787
@@ -54,4 +54,8 @@ jobs:
       run: |
         curl 127.0.0.1:8787
         cd e2e
-        cargo run
+        cargo run || echo "e2e failed"
+        echo "dev.txt"
+        cat dev.txt
+        echo "driver.txt"
+        cat driver.txt
